# Filtering and ordering panda dataframes

1. Initialise and reading file path

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"/Users/mattmeredith/Downloads/world-data-2023.csv")

2. Filter by single condition or specific values

In [64]:
df[df['Fertility Rate'] >= 5]

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
26,Burkina Faso,76,BF,44.20%,"274,200","11,000",37.93,226.0,Ouagadougou,"3,418",...,36.10%,0.08,"20,321,378",66.40%,15.00%,41.30%,6.26%,"6,092,349",12.238333,-1.561593
27,Burundi,463,BI,79.20%,"27,830","31,000",39.01,257.0,Bujumbura,495,...,19.10%,0.10,"11,530,580",79.20%,13.60%,41.20%,1.43%,"1,541,177",-3.373056,29.918886
34,Chad,13,TD,39.70%,"1,284,000","35,000",42.17,235.0,N'Djamena,"1,016",...,56.40%,0.04,"15,946,876",70.70%,NaN,63.50%,1.89%,"3,712,273",15.454166,18.732207
45,Democratic Republic of the Congo,40,CD,11.60%,"2,344,858","134,000",41.18,243.0,Kinshasa,"2,021",...,37.40%,0.07,"86,790,567",63.50%,10.70%,50.70%,4.24%,"39,095,679",-4.038333,21.758664
62,The Gambia,239,GM,59.80%,"11,300","1,000",38.54,220.0,Banjul,532,...,20.30%,0.10,"2,347,706",59.40%,9.40%,48.40%,9.06%,"1,453,958",13.443182,-15.310139
105,Mali,17,ML,33.80%,"1,240,192","18,000",41.54,223.0,Bamako,"3,179",...,46.30%,0.13,"19,658,031",70.80%,11.60%,54.50%,7.22%,"8,479,688",17.570692,-3.996166
125,Niger,19,NE,36.10%,"1,267,000","10,000",46.08,227.0,Niamey,"2,017",...,52.30%,0.04,"23,310,715",72.00%,11.80%,47.20%,0.47%,"3,850,231",17.607789,8.081666
126,Nigeria,226,NG,77.70%,"923,768","215,000",37.91,234.0,Abuja,"120,369",...,72.20%,0.38,"200,963,599",52.90%,1.50%,34.80%,8.10%,"102,806,948",9.081999,8.675277
160,Somalia,25,SO,70.30%,"637,657","20,000",41.75,252.0,Mogadishu,645,...,NaN,0.02,"15,442,905",47.40%,0.00%,NaN,11.35%,"7,034,861",5.152149,46.199616

In [15]:
specificCountries = ['Australia', 'India']

In [16]:
df[df['Country'].isin(specificCountries)]

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
8,Australia,3,AU,48.20%,"7,741,220","58,000",12.60,61.0,Canberra,"375,908",...,19.60%,3.68,"25,766,605",65.50%,23.00%,47.40%,5.27%,"21,844,756",-25.274398,133.775136
77,India,464,IN,60.40%,"3,287,263","3,031,000",17.86,91.0,New Delhi,"2,407,672",...,65.10%,0.86,"1,366,417,754",49.30%,11.20%,49.70%,5.36%,"471,031,528",20.593684,78.962880

In [25]:
df[df['Country'].str.contains('Island')]

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
107,Marshall Islands,329,MH,63.90%,181,NaN,29.03,692.0,Majuro,143,...,10.00%,0.42,"58,791",NaN,17.80%,65.90%,NaN,"45,514",7.131474,171.184478
159,Solomon Islands,25,SB,3.90%,"28,896",NaN,32.44,677.0,Honiara,169,...,3.30%,0.19,"669,823",83.80%,29.50%,32.00%,0.58%,"162,164",-9.645710,160.156194

3. Setting index of a dataframe

In [32]:
df2 = df.set_index('Abbreviation')

4. Filtering dataframe with .filter() and like

In [41]:
df2.filter(like = 'X', axis = 0)

,Country,Density\n(P/Km2),Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
Abbreviation,,,,,,,,,,,,,,,,,,,,,
MX,Mexico,66,54.60%,"1,964,375","336,000",17.6,52.0,Mexico City,"486,406",141.54,...,41.40%,2.38,"126,014,024",60.70%,13.10%,55.10%,3.42%,"102,626,859",23.634501,-102.552784

5. Locating specific data with loc[] and specific index position with iloc[]

In [66]:
df2.loc['MX']

Country                                                   Mexico
Density\n(P/Km2)                                              66
Agricultural Land( %)                                     54.60%
Land Area(Km2)                                         1,964,375
Armed Forces size                                        336,000
Birth Rate                                                  17.6
Calling Code                                                52.0
Capital/Major City                                   Mexico City
Co2-Emissions                                            486,406
CPI                                                       141.54
CPI Change (%)                                             3.60%
Currency-Code                                                MXN
Fertility Rate                                              2.13
Forested Area (%)                                         33.90%
Gasoline Price                                            $0.73
GDP                                          $1,258,286,717,125
Gross primary education enrollment (%)                   105.80%
Gross tertiary education enrollment (%)                   40.20%
Infant mortality                                            11.0
Largest city                                         Mexico City
Life expectancy                                             75.0
Maternal mortality ratio                                    33.0
Minimum wage                                              $0.49
Official language                                           None
Out of pocket health expenditure                          41.40%
Physicians per thousand                                     2.38
Population                                           126,014,024
Population: Labor force participation (%)                 60.70%
Tax revenue (%)                                           13.10%
Total tax rate                                            55.10%
Unemployment rate                                          3.42%
Urban_population                                     102,626,859
Latitude                                               23.634501
Longitude                                            -102.552784
Name: MX, dtype: object

In [56]:
df.iloc[6]

Country                                              Argentina
Density\n(P/Km2)                                            17
Abbreviation                                                AR
Agricultural Land( %)                                   54.30%
Land Area(Km2)                                       2,780,400
Armed Forces size                                      105,000
Birth Rate                                               17.02
Calling Code                                              54.0
Capital/Major City                                Buenos Aires
Co2-Emissions                                          201,348
CPI                                                     232.75
CPI Change (%)                                          53.50%
Currency-Code                                              ARS
Fertility Rate                                            2.26
Forested Area (%)                                        9.80%
Gasoline Price                                          $1.10
GDP                                          $449,663,446,954
Gross primary education enrollment (%)                 109.70%
Gross tertiary education enrollment (%)                 90.00%
Infant mortality                                           8.8
Largest city                                      Buenos Aires
Life expectancy                                           76.5
Maternal mortality ratio                                  39.0
Minimum wage                                            $3.35
Official language                                      Spanish
Out of pocket health expenditure                        17.60%
Physicians per thousand                                   3.96
Population                                          44,938,712
Population: Labor force participation (%)               61.30%
Tax revenue (%)                                         10.10%
Total tax rate                                         106.30%
Unemployment rate                                        9.79%
Urban_population                                    41,339,571
Latitude                                            -38.416097
Longitude                                           -63.616672
Name: 6, dtype: object

6. Order by .sort_values()

In [63]:
df[df['Fertility Rate'] > 5].sort_values(by='Birth Rate', ascending=False)

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,...,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
125,Niger,19,NE,36.10%,"1,267,000","10,000",46.08,227.0,Niamey,"2,017",...,52.30%,0.04,"23,310,715",72.00%,11.80%,47.20%,0.47%,"3,850,231",17.607789,8.081666
34,Chad,13,TD,39.70%,"1,284,000","35,000",42.17,235.0,N'Djamena,"1,016",...,56.40%,0.04,"15,946,876",70.70%,NaN,63.50%,1.89%,"3,712,273",15.454166,18.732207
160,Somalia,25,SO,70.30%,"637,657","20,000",41.75,252.0,Mogadishu,645,...,NaN,0.02,"15,442,905",47.40%,0.00%,NaN,11.35%,"7,034,861",5.152149,46.199616
105,Mali,17,ML,33.80%,"1,240,192","18,000",41.54,223.0,Bamako,"3,179",...,46.30%,0.13,"19,658,031",70.80%,11.60%,54.50%,7.22%,"8,479,688",17.570692,-3.996166
45,Democratic Republic of the Congo,40,CD,11.60%,"2,344,858","134,000",41.18,243.0,Kinshasa,"2,021",...,37.40%,0.07,"86,790,567",63.50%,10.70%,50.70%,4.24%,"39,095,679",-4.038333,21.758664
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.73,244.0,Luanda,"34,693",...,33.40%,0.21,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.202692,17.873887
27,Burundi,463,BI,79.20%,"27,830","31,000",39.01,257.0,Bujumbura,495,...,19.10%,0.10,"11,530,580",79.20%,13.60%,41.20%,1.43%,"1,541,177",-3.373056,29.918886
62,The Gambia,239,GM,59.80%,"11,300","1,000",38.54,220.0,Banjul,532,...,20.30%,0.10,"2,347,706",59.40%,9.40%,48.40%,9.06%,"1,453,958",13.443182,-15.310139
26,Burkina Faso,76,BF,44.20%,"274,200","11,000",37.93,226.0,Ouagadougou,"3,418",...,36.10%,0.08,"20,321,378",66.40%,15.00%,41.30%,6.26%,"6,092,349",12.238333,-1.561593
126,Nigeria,226,NG,77.70%,"923,768","215,000",37.91,234.0,Abuja,"120,369",...,72.20%,0.38,"200,963,599",52.90%,1.50%,34.80%,8.10%,"102,806,948",9.081999,8.675277